### ISSUE TITLE
exoplayer/WidevineModularSampleApp doesn't use WidevinePlugin

### ISSUE THREAD

**Issue by hotchemi** [BrightcoveOS/android-player-samples#113]
It seems brightcove-exoplayer/WidevineModularSampleApp doesn't use WidevinePlugin inside of the Activity, is it correct?

https://github.com/BrightcoveOS/android-player-samples/tree/master/brightcove-exoplayer/WidevineModularSampleApp

**Comment by BCjwhisenant** [comment]
Hi @hotchemi 
This is correct, the WidevineModularSampleApp does not use the Widevine Plugin.
Since this sample uses the BrightcoveExoPlayerVideoView, and since ExoPlayer supports Widevine Modular (in Android 4.3+) out of the box, there is no need to use our Widevine plugin.
We also have the [BasicWidevineSampleApp](https://github.com/BrightcoveOS/android-player-samples/tree/master/BasicWidevineSampleApp/src/main), which does use our Widevine plugin.

**Comment by hotchemi** [comment]
Thx!
