### ISSUE TITLE
pre roll is not localized for portuguese langyage

### ISSUE THREAD

**Issue by sreekanth627** [BrightcoveOS/android-player-samples#133]
Hey i need to localize pre roll ad for all locales. with the help of setLanguage() method i made it localized except for Portuguese. For Portuguese i am passing "pt" as language code. But pre roll is coming as english. Please look in to this issue. If i am missing anything here, please suggest me.

I am using following lines
 ImaSdkSettings settings = new ImaSdkSettings();
  settings.setLanguage("pt");
googleIMAComponent = new GoogleIMAComponent(brightcoveVideoView, eventEmitter, true, settings);

**Comment by sergiomartinez4** [comment]
hi @sreekanth627 

That seems to be an issue with the Google IMA SDK.
According to the [IMA SDK reference](https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/api/reference/com/google/ads/interactivemedia/v3/api/ImaSdkSettings.html#setLanguage(java.lang.String)) "This must be a 2-letter ISO 639-1 language code", so  "pt" should work. However I found that in order to use Portuguese you must use "pt_pt" or "pt_br" for Portuguese from Portugal or Portuguese from Brazil, respectively.

For further questions related to this particular issue, I recommend contacting Google IMA support.

**Comment by sreekanth627** [comment]
thanks  @sergiomartinez4 . It is working :).
