### ISSUE TITLE
Video flashes outside the bounds of the video player for a second when a video is added.

### ISSUE THREAD

**Issue by frankkubista** [BrightcoveOS/android-player-samples#202]
When adding a video to the BrightcoveExoPlayerVideoView the first frame of the video flashes on the screen behind the video player and outside the bounds of the view for a second.

[Video Flash.mp4.zip](https://github.com/BrightcoveOS/android-player-samples/files/3617790/Video.Flash.mp4.zip)

**Comment by sergiomartinez4** [comment]
Hi @frankkubista 
Sorry for the delayed response. I highly suggest to use the public forum instead as that's more actively monitored: https://groups.google.com/forum/#!forum/brightcove-native-player-sdks

You may also find your answers there by looking at similar issues. For example, it seems your issue is similar as to this forum question, and the fix may apply to you as well: https://groups.google.com/d/msg/brightcove-native-player-sdks/yq4TYj6Oes8/mz_A4F91CAAJ

good luck!
