### ISSUE TITLE
full screen doesn't work when using scrollview

### ISSUE THREAD

**Issue by HasanElHefnawy** [BrightcoveOS/android-player-samples#211]
full screen doesn't work when the parent layout is ScrollView. Here is a sample project you can check.
https://github.com/HasanElHefnawy/brightcove-inside-scrollview

**Comment by sergiomartinez4** [comment]
Hi @HasanElHefnawy,
I took a quick look at your sample. I'm able to make the video full screen. The only difference I saw was that when going full screen, the video will go to the top. But that is because of the layout_gravity.
Note that when a video does not have the same aspect ratio as the device, there will be white bands above and below the video (white since that's the background color).

For testing purposes, I added the `android:layout_gravity="center_horizontal|center_vertical"` to the constraint layout and now I was getting exactly the same behavior as the other sample apps. Granted, the video non-full screen is center in the activity.

Another thing I noticed was that the manifest didn't have a config changes `android:configChanges="orientation|screenSize"`. You need this to avoid destroying and re-creating the player when rotating the device.

**Comment by HasanElHefnawy** [comment]
@sergiomartinez4 
Thanks a lot dear for reply. It seems this issue occurs with my device Lenovo A7010 VIBE K4 Note (API 22). Once I press the full_screen button, the height of BrightcoveExoPlayerVideoView becomes zero. I could overcome this issue by using this code

`        DisplayMetrics displayMetrics = getResources().getDisplayMetrics();
        brightcoveVideoView.getEventEmitter().on(EventType.DID_ENTER_FULL_SCREEN, event -> {
            brightcoveVideoView.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, displayMetrics.heightPixels));
        });
`

**Comment by sergiomartinez4** [comment]
@HasanElHefnawy 
interesting it happens on that device in particular. I wonder if this is related to the constraint layout, or if it also happens with, say, a linear layout...
in any case, thanks for sharing the code!
