### ISSUE TITLE
Change pause icon

### ISSUE THREAD

**Issue by UserSty** [BrightcoveOS/android-player-samples#214]
How can I change the pause icon?

I would like to set different images for the play button.

When I set:
```
 <style name="BrightcoveControlBar.Custom">
        <item name="brightcove_play_image">@drawable/play_icon</item>
        <item name="brightcove_pause_image">@drawable/pause_icon</item>
    </style>
```
the button play/pause doesn't react

**Comment by sergiomartinez4** [comment]
Hi @UserSty 
There appears to be a bug when setting the drawables this way. I filed the bug in our backlog but I'm not sure when we'd have time to work on this.

There's another way you can add a button. You could add the new icons (SVG) in the fontawesome-webfont.ttf we use in the SDK. The latest is here:
[fontawesome-webfont.ttf.zip](https://github.com/BrightcoveOS/android-player-samples/files/4416937/fontawesome-webfont.ttf.zip)

You can use FontForge to do this (https://fontforge.org/en-US/downloads) or any other software of your preference to edit TFF font files.
Once you add it and export it, add the file to your assets folder using the same name, so that it overrides the existing one and picks up the new changes. Then you will need to use replace the string values for play and pause using the new HEX values where you added the icons in the TFF file:
```
    <string name="brightcove_controls_play">&#xf04b;</string>
    <string name="brightcove_controls_pause">&#xf04c;</string>
```
Hope this helps. Let me know if you have any question

**Comment by BCjwhisenant** [comment]
Closing, this as resolved. Please open a [support ticket](https://sdks.support.brightcove.com/support/opening-case-with-brightcove-support.html) if you having further issues.
