### ISSUE TITLE
Can you give an example of nested recyclerview

### ISSUE THREAD

**Issue by Faiyyaz** [BrightcoveOS/android-player-samples#239]
Hi,

Thank you for such a great library.

I have a requirements like instagram feed where a user can upload single or multiple media in a post. Single works fine by using your videoList example but suppose if I have a horizontal recyclerview or viewpager2 as a view item then how can we achieve proper stopping and playing of the video players?

**Comment by hadilo** [comment]
i need example with viewpager2 too, please

**Comment by BCjwhisenant** [comment]
Hello @Faiyyaz @hadilo ,
Thank you for your interest in the Brightcove Native SDK for Android. Unfortunately, this Issues list is less-often reviewed than our usual support request flow. That said, we don't currently have support for uploads in our SDK.
If you wouldn't mind, please [file a support request](https://sdks.support.brightcove.com/support/opening-case-with-brightcove-support.html) so that we can prioritize it appropriately.

**Comment by BCjwhisenant** [comment]
Closing this. Requested that a Support ticket be opened.
