### ISSUE TITLE
Jetpack compose ableness

### ISSUE THREAD

**Issue by diofelpallega** [BrightcoveOS/android-player-samples#242]
Hi I would like to know if Brightcove sdk can be integrated with jetpack compose built application.

**Comment by alexklars** [comment]
Hi. The same question. We have integrated  Brightcove  into our application on Jetpack Compose using `BrightcoveExoPlayerVideoView` and [`AndroidView` composable](https://developer.android.com/reference/kotlin/androidx/compose/ui/viewinterop/package-summary#AndroidView(kotlin.Function1,androidx.compose.ui.Modifier,kotlin.Function1)). Everything works, but it seems that the code needs some improvement, since we get memory leaks on the screen with the list of Brightcove videos. Considering that Compose is gaining popularity, I think it makes sense to add support to the library, or at least add an example of how it can be integrated using `AndroidView` composable.

**Comment by dvrajput96-yml** [comment]
> Hi. The same question. We have integrated Brightcove into our application on Jetpack Compose using `BrightcoveExoPlayerVideoView` and [`AndroidView` composable](https://developer.android.com/reference/kotlin/androidx/compose/ui/viewinterop/package-summary#AndroidView(kotlin.Function1,androidx.compose.ui.Modifier,kotlin.Function1)). Everything works, but it seems that the code needs some improvement, since we get memory leaks on the screen with the list of Brightcove videos. Considering that Compose is gaining popularity, I think it makes sense to add support to the library, or at least add an example of how it can be integrated using `AndroidView` composable.

I completely agree on this, we need compose support or proper documentation.

**Comment by nandovelazquez** [comment]
Hi. We have some stories in our backlog to offer support for Jetpack Compose, but we do not have a ETA yet.

When the support is implemented it will be release-noted in the SDK and announced in our [mailing list](https://groups.google.com/g/brightcove-native-player-sdks/c/vwrEbqB6okM).
